apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msa-demo-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: msa.local
      http:
        paths:
          - path: /a
            pathType: Prefix
            backend:
              service:
                name: service-a
                port:
                  number: 8081
          - path: /b
            pathType: Prefix
            backend:
              service:
                name: service-b
                port:
                  number: 8082
